Adapting buildconf to install from GMV

diff --git a/install_esrocos b/install_esrocos
--- a/install_esrocos
+++ b/install_esrocos
@@ -1,10 +1,32 @@
 #! /bin/sh
 
-CONF_URL=https://github.com/ESROCOS/buildconf.git
-AUTOPROJ_CONFIG_URL=https://raw.githubusercontent.com/ESROCOS/buildconf/master/config.yml
-AUTOPROJ_BOOTSTRAP_URL=https://rock-robotics.org/master/autoproj_bootstrap
+# URLs to install from GitHub
+#CONF_URL=https://github.com/ESROCOS/buildconf.git
+#AUTOPROJ_CONFIG_URL=https://raw.githubusercontent.com/ESROCOS/buildconf/master/config.yml
+#AUTOPROJ_BOOTSTRAP_URL=https://rock-robotics.org/master/autoproj_bootstrap
+#DOWNLOAD_AUTOPROJ_CONFIG=true
 
-#Which ESROCOS buildconf branch to check out
+# URLs to install from GMV's GitLab
+CONF_URL=https://spass-git-ext.gmv.com/OBA/MOSAR/ESROCOS/buildconf
+AUTOPROJ_CONFIG_URL=$(realpath $(dirname $0))/config.yml
+AUTOPROJ_BOOTSTRAP_URL=$(realpath $(dirname $0))/autoproj_bootstrap
+DOWNLOAD_AUTOPROJ_CONFIG=false
+
+# DOWNLOAD_AUTOPROJ_CONFIG indicates that the autoproj files can be downloaded from a public repo
+# When using a private repo, the files must be copied from a local path instead
+
+if test $DOWNLOAD_AUTOPROJ_CONFIG != true ; then
+    if ! test -f $AUTOPROJ_CONFIG_URL; then
+        echo "config.yml not found in the same directory as install_esrocos"
+        exit 1
+    fi
+    if ! test -f $AUTOPROJ_BOOTSTRAP_URL; then
+        echo "autoproj_bootstrap not found in the same directory as install_esrocos"
+        exit 1
+    fi
+fi
+
+#Which ESROCOS buildconf branch to check out 
 if [[ -z $ESROCOS_BRANCH ]]; then
   ESROCOS_BRANCH="master"
 fi
@@ -14,17 +36,11 @@ echo "checking out branch: $ESROCOS_BRANCH"
 RUBY=ruby
 BOOTSTRAP_ARGS=
 
+set -e
+
 mkdir -p ~/esrocos_workspace/.autoproj
 
 cd ~/esrocos_workspace
-
-if test -n "$1" && test "$1" != "dev" && test "$1" != "localdev"; then
-    RUBY=$1
-    shift 1
-    RUBY_USER_SELECTED=1
-fi
-
-set -e
 
 if ! which $RUBY > /dev/null 2>&1; then
     echo "cannot find the ruby executable. On Ubuntu 16.04 and above, you should run"
@@ -64,17 +80,22 @@ fi
 # FINALLY NO MORE RUBY
 # DOWNLOAD AUTOPROJ
 
+if which wget > /dev/null; then
+    DOWNLOADER=wget
+elif which curl > /dev/null; then
+    DOWNLOADER=curl
+else
+    echo "I can find neither curl nor wget, either install one of these or"
+    echo "download the following script yourself, and re-run this script"
+    exit 1
+fi
+
 if ! test -f $PWD/autoproj_bootstrap; then
-    if which wget > /dev/null; then
-        DOWNLOADER=wget
-    elif which curl > /dev/null; then
-        DOWNLOADER=curl
+    if $DOWNLOAD_AUTOPROJ_CONFIG = true ; then
+        $DOWNLOADER $AUTOPROJ_BOOTSTRAP_URL
     else
-        echo "I can find neither curl nor wget, either install one of these or"
-        echo "download the following script yourself, and re-run this script"
-        exit 1
+        cp $AUTOPROJ_BOOTSTRAP_URL .
     fi
-    $DOWNLOADER $AUTOPROJ_BOOTSTRAP_URL
 fi
 
 # DECIDES HOW TO DOWNLOAD STUFF
@@ -121,7 +142,11 @@ done
 
 cd ~/esrocos_workspace/.autoproj
 
-wget $AUTOPROJ_CONFIG_URL
+if $DOWNLOAD_AUTOPROJ_CONFIG = true ; then
+    $DOWNLOADER $AUTOPROJ_CONFIG_URL
+else
+    cp $AUTOPROJ_CONFIG_URL .
+fi
 
 cd ..
 
